travis:
  secure:
    BINSTAR_TOKEN: noPqqTR+PYVLTufqRQv/nBCBk9P88S0OdSBnf3zrG9sdO3Yrp8V0wueILT547y0YX+yEjLFP1CBi9lsF+gd9T7kNfSLUZuK5YjGyB6SGbXQWH4O/3d3dFrvp2OuYzJqnYXbV1g33LARQoVrtjDVlWmeavjAYLfpqvcY1ZgZiZwbKlBqLfup7umbqPdr/RxDR2neI3ZmG1pHMR2HYF1lDqKpbpf0e+aKF+QD6LXCw71vbciga9dE1Jnm31z+9Vw6P1LU5vieGdBBxY1mbloXYSbdoDg3E5p+lQSYNSPT5ytLXPiPtWwEgky/ssHF4WPN9Cg6g1I8f0G8wFPMZvxYSVJid+JpkPA7YzcAGHA7CE9w2TcRcWf36qF4kyI0x/Lm/0xXYVDxHixu6twMVrZFDQ0+4nPxIAzC5/T+boMmd3jmVc3UYujt4IZvqA46dsCepIcT08BFVn3LFOyyAEXVBeJjz6q5vNPtxlXdQSb0f+XNSBfY+4ZbRQdwiJP9tjtHlMHETWofBPTwVKp5VcgUicNEZOqQlnIp0rM4LdVI8EFDypwxGiE4iRaE74fv3m0ZR7FFbeygA28ZrHZf+QToxyY/rrhf94VVfV38tyxq4qmaq9+9diJR3tLUqVzuPMWPBiLNCME4seGmTC/p9zJaxEQLsJm4hhEZNQdw8OMXqWqo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
